### ISSUE TITLE
Cannot open included file in VS Code

### ISSUE THREAD

**Issue by faybs** [grahambates/m68k-lsp#14]
When using the Visual Studio Code plugin, you get an error when trying to open an included file by clicking on it, because the path the plugin presents to VS Code is escaped.

To reproduce this issue, create a directory c:\tmp and put two files in it, test.asm and test.inc.

```
; test.inc

somelabel    equ 1
```
```
; test.asm

   include "test.inc"
```

If you open test.asm in Visual Studio Code and set the file type to M68k-Assembly, you'll see that "test.inc" is a hyperlink.

![image](https://github.com/grahambates/m68k-lsp/assets/25086308/2b48a740-599a-49bc-9c1e-e6af62c13514)

If you ctrl+click on this hyperlink it should open the test.inc file, but instead you get this error:

![image](https://github.com/grahambates/m68k-lsp/assets/25086308/d97b625c-e2b7-43b7-84ea-bbee4612191d)

As you can see, the problem is that the path is escaped and so VS Code cannot find the file.

**Comment by grahambates** [comment]
This is fixed in the latest version of the extension. It was happening because the protocol expects the path as a URI, not a system file path. On Mac and Linux it was working regardless, but as you saw Windows was getting upset.

**Comment by faybs** [comment]
Thanks!
