### ISSUE TITLE
Possibility of enhancing LSP features using vasm

### ISSUE THREAD

**Issue by dansalvato** [grahambates/m68k-lsp#2]
![2022-05-08_00-54-37](https://user-images.githubusercontent.com/7810794/167345674-50cd4a6c-64c5-479d-a17d-f686dd04dbc2.png)

This idea is inspired by [prb28/vscode-amiga-assembly](https://github.com/prb28/vscode-amiga-assembly), which parses vasm output on build and uses it for linting. I tested something similar by writing a script that parses the vasm output into a standard errorformat, then giving it to a generic lint plugin.

More importantly, vasm seamlessly builds to WebAssembly (using emscripten) and can be run via node without any issues. Aside from linting, maybe there is some other good functionality that could be leveraged, such as using its symbol map/listing file generation to provide information about symbol definitions to the LSP?

This is kind of an open-ended suggestion, because I'm not sure how far you're planning to go with your own parser, or what gaps you think could be filled with vasm. But I thought I would mention my findings in case you think it might be useful to explore.

**Comment by grahambates** [comment]
Yeah, I've been thinking about this. The idea of using wasm is a really good one and I think I'll give it a try.

I did have a few reservations that have put me off so far:
- Not every assembly source file can necessarily be built stand-alone in the way that say, a C source file can. A couple of examples that come to mind are:
  - Includes are relative to the entry point, not the source file where they occur. If you have include files in another dir, which themselves have includes, this could present issues. To be fair though, this could mostly be solved by passing vasm an include path of the project root.
  - If your main source file has several includes they can reference each other's symbols even if they don't explicilty include each other. Arguably this is bad practice though.
- It's not necessarily a given that everyone's cross-assembling using vasm. A valid use case would be to edit files in a modern editor but assemble on a native assembler e.g. Devpac as AsmOne. In this case you might be using non-vasm compatible syntax. Simplest thing for this would be to allow vasm diagnostics to be turned off in config.
- The LSP would need to know your project specific command-line options for vasm. Maybe this isn't so bad though.
- I didn't want a dependency on vasm binaries but your wasm suggestion negates this.

Another reason that I wasn't sure if this is 100% necessary (which might be useful to you) is that in Neovim I'm already able to get diagnostics from vasm errors using the `:make` command and `errorformat`:
```
set errorformat+=%E,%C%s\ %n\ in\ line\ %l\ of\ \"%f\":\ %m,%Z%s
```

Thanks again for the suggestion! I'll definitely spend some more time looking at this.

**Comment by grahambates** [comment]
@dansalvato do you have any pointers on getting a working Web Assembly build of vasm and calling it from node? I was able to build the project using `emmake` but the resulting script doesn't seem to want to open any files. It's probably something simple as I'm a bit of a wasm noob!

**Comment by dansalvato** [comment]
Same here, and I ran into the same issue—it turns out wasm uses a sandboxed filesystem by default, but if running in a Node environment, those restrictions can be lifted by using Node's FS functions. I got it to work after setting these linker flags in the makefile:
```
LDFLAGS = -lm -lnodefs.js -sENVIRONMENT=node -sFORCE_FILESYSTEM -sNODERAWFS
```

**Comment by grahambates** [comment]
Yeah that worked perfectly. Thanks for your help.
