### ISSUE TITLE
Parser and formatter get confused by backslashes in macro code

### ISSUE THREAD

**Issue by dansalvato** [grahambates/m68k-lsp#4]
Perhaps the backspaces are not being treated literally, but are instead considered part of an escape sequence? A couple examples in my code:

```
; Original line
                CFX_\1FILL
; Gets formatted as this
                CFX_            \1FILL

; Original line
Color\<REPTN>:  dc.l               0
; Gets formatted as this
Color:\                                                          <REPTN>:  dc.l               0
```

The parser also reports a "Parser error" diagnostic when trying to parse the original line, despite it being valid.

**Comment by grahambates** [comment]
Thanks for flagging. I'll look into this.
