### ISSUE TITLE
`onDidChangeConfiguration` overwrites all settings instead of just changed settings, breaking Helix support

### ISSUE THREAD

**Issue by dansalvato** [grahambates/m68k-lsp#9]
https://github.com/grahambates/m68k-lsp/blob/ea0a308f79aba0e7cff8afee71e6749f87f99671/server/src/providers/ConfigurationProvider.ts#L10-L15

According to LSP spec, `onDidChangeConfiguration` only provides *changed* settings, but the above function assumes that all settings are being provided.

This discrepancy causes `m68k-lsp-server` to not work properly in the Helix editor, because Helix sends multiple `onDidChangeConfiguration` calls which causes the LSP to overwrite the user's initialization options with the defaults.

I confirmed that this workaround successfully fixes Helix support:
```ts
  async onDidChangeConfiguration() {
    const oldConfig = this.ctx.config;
    const newConfig = await this.ctx.connection.workspace.getConfiguration(
      "m68k"
    );
    this.ctx.config = {
      ...oldConfig,
      ...newConfig,
      format: {
        ...oldConfig.format,
        ...newConfig?.format,
        align: {
          ...oldConfig.format.align,
          ...newConfig?.format?.align,
        },
      },
      vasm: {
        ...oldConfig.vasm,
        ...newConfig?.vasm,
      },
    };
  }
```

**Comment by grahambates** [comment]
Thanks for this. I'll get it fixed.
